---

alpaca_from_source: no

alpaca_version: master
alpaca_clone_directory: /opt/alpaca

alpaca_karaf_repos:
  - mvn:ca.islandora.alpaca/islandora-karaf/LATEST/xml/features

alpaca_features:
  - islandora-http-client
  - islandora-connector-broadcast
  - islandora-indexing-triplestore
  - islandora-indexing-fcrepo

alpaca_karaf_dir: /opt/karaf
alpaca_karaf_etc_dir: "{{ alpaca_karaf_dir }}/etc"
alpaca_karaf_user: karaf
alpaca_local_mvn_path: /opt/maven/repo

alpaca_settings:
  - pid: ca.islandora.alpaca.connector.broadcast
    settings:
      input.stream: activemq:queue:islandora-connector-broadcast
  - pid: ca.islandora.alpaca.indexing.triplestore
    settings:
      error.maxRedeliveries: 10
      input.stream: activemq:queue:islandora-indexing-triplestore
      triplestore.baseUrl: http://localhost:8080/bigdata/namespace/islandora/sparql
