---
galaxy_info:
  author: Islandora
  description: Ansible Galaxy role for installing Blazegraph
  company: Islandora Foundation
  license: MIT
  min_ansible_version: 2.0
  max_ansible_version: 2.3
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  - name: EL
    versions:
      - 7
  galaxy_tags:
    - islandora
    - CLAW
    - blazegraph
    - bigdata
    - triplestore
    - rdf
    - semantic
    - web
    - installer
dependencies: []
