crayfish_version_tag: 0.0.14

crayfish_services:
  - Gemini
  - Houdini
  - Milliner
  - Hypercube
  - Homarus

crayfish_install_dir: /var/www/html/Crayfish

crayfish_syn_token: islandora

# possible options: mysql, pgsql
crayfish_db: mysql
crayfish_pgsql_user: postgres
crayfish_db_user: crayfish
crayfish_db_password: islandora
crayfish_db_name: gemini
crayfish_db_driver: "{% if crayfish_db == 'mysql' %}pdo_mysql{% elif crayfish_db == 'pgsql' %}pdo_pgsql{% endif %}"
crayfish_db_port: "{% if crayfish_db == 'mysql' %}3306{% elif crayfish_db == 'pgsql' %}5432{% endif %}"

# Gemini default config
crayfish_gemini_log_file: /var/log/islandora/gemini.log
crayfish_gemini_log_level: DEBUG

crayfish_gemini_debug: TRUE

crayfish_gemini_fedora_base_url: http://localhost:8080/fcrepo/rest

crayfish_gemini_jwt_enabled: TRUE
crayfish_gemini_jwt_config: ../syn-settings.xml

crayfish_gemini_db_options:
  driver: "{{ crayfish_db_driver }}"
  host: 127.0.0.1
  port: "{{ crayfish_db_port }}"
  dbname: "{{ crayfish_db_name }}"
  user: "{{ crayfish_db_user }}"
  password: "{{ crayfish_db_password }}"

# Houdini default config
crayfish_houdini_log_file: /var/log/islandora/houdini.log
crayfish_houdini_log_level: DEBUG

crayfish_houdini_jwt_enabled: TRUE
crayfish_houdini_jwt_config: ../syn-settings.xml

crayfish_houdini_fedora_base_url: http://localhost:8080/fcrepo/rest

crayfish_houdini_executable_config:
  executable: convert
  formats:
    valid:
      - image/jpeg
      - image/png
      - image/tiff
      - image/jp2
    default: image/jpeg

# Hypercube default config
crayfish_hypercube_log_file: /var/log/islandora/hypercube.log
crayfish_hypercube_log_level: DEBUG

crayfish_hypercube_jwt_enabled: TRUE
crayfish_hypercube_jwt_config: ../syn-settings.xml

crayfish_hypercube_fedora_base_url: http://localhost:8080/fcrepo/rest
crayfish_hypercube_executable: tesseract

# Milliner default config
crayfish_milliner_log_file: /var/log/islandora/milliner.log
crayfish_milliner_log_level: DEBUG

crayfish_milliner_jwt_enabled: TRUE
crayfish_milliner_jwt_config: ../syn-settings.xml

crayfish_milliner_debug: TRUE

crayfish_milliner_fedora_base_url: http://localhost:8080/fcrepo/rest
crayfish_milliner_drupal_base_url: http://localhost:8000
crayfish_milliner_gemini_base_url: http://localhost:8000/gemini
crayfish_milliner_modified_date_predicate: http://schema.org/dateModified

crayfish_milliner_db_options:
  driver: "{{ crayfish_db_driver }}"
  host: 127.0.0.1
  port: "{{ crayfish_db_port }}"
  dbname: "{{ crayfish_db_name }}"
  user: "{{ crayfish_db_user }}"
  password: "{{ crayfish_db_password }}"

# OS Dependent variables set in vars can be overridden here
# crayfish_user: www-data
# httpd_conf_directory: /etc/apache2
# crayfish_packages:
#   - ImageMagick

php_packages_extra:
  - php7.0-mysql
  - php7.0-pgsql


# homarus
crayfish_homarus_log_file: /var/log/islandora/homarus.log
crayfish_homarus_log_level: DEBUG

crayfish_homarus_jwt_enabled: TRUE
crayfish_homarus_jwt_config: ../syn-settings.xml

crayfish_homarus_fedora_base_url: http://localhost:8080/fcrepo/rest

crayfish_homarus_executable_config:
  executable: ffmpeg
  mime_types:
    valid:
      - video/mp4
      - video/x-msvideo
      - video/ogg
      - audio/x-wav
      - audio/mpeg
      - audio/aac
    default: video/mp4
  mime_to_format:
    valid:
      - video/mp4_mp4
      - video/x-msvideo_avi
      - video/ogg_ogg
      - audio/x-wav_wav
      - audio/mpeg_mp3
      - audio/aac_m4a
    default: mp4
