---

- name: Make sure java packages are installed
  apt:
    name: "{{ karaf_java_packages|join(',') }}"
    state: present
    update_cache: yes

- name: Expand Karaf Tarball
  unarchive:
    src: "{{ karaf_staging_folder }}/apache-karaf-{{ karaf_version }}.tar.gz"
    dest: "{{ karaf_install_folder }}"
    owner: "{{ karaf_user }}"
    group: "{{ karaf_user }}"
    remote_src: yes
    creates: "{{ karaf_install_folder }}/apache-karaf-{{ karaf_version }}"

- name: Set Karaf Permissions
  file:
    state: directory
    path: "{{ karaf_install_folder }}/apache-karaf-{{ karaf_version }}"
    owner: "{{ karaf_user }}"
    group: "{{ karaf_user }}"

- name: Make Karaf Symlink
  file:
    state: link
    src: "{{ karaf_install_folder }}/apache-karaf-{{ karaf_version }}"
    dest: "{{ karaf_install_symlink }}"
    owner: "{{ karaf_user }}"
    group: "{{ karaf_user }}"

