---

- name: Create Gemini DB User (pgsql)
  postgresql_user:
    name: "{{ crayfish_db_user }}"
    password: "{{ crayfish_db_password }}"

- name: Create Gemini DB (pgsql)
  postgresql_db:
    name: "{{ crayfish_db_name }}"
    state: present
    owner: "{{ crayfish_db_user }}"
  register: gemini_db_exists

- name: Grab Gemini db schema (pgsql)
  template:
    src: "database/gemini-pgsql.sql"
    dest: "/tmp/gemini.sql"
  when: gemini_db_exists.changed

- name: Install Gemini db schema (pgsql)
  command: psql -d {{ crayfish_db_name }} -f /tmp/gemini.sql
  when: gemini_db_exists.changed
