---

- include: db-mysql.yml
  tags:
    - crayfish
    - crayfish-db
  when: crayfish_db == 'mysql'

- include: db-pgsql.yml
  tags:
    - crayfish
    - crayfish-db
  when: crayfish_db == 'pgsql'
  become_user: "{{ crayfish_pgsql_user }}"

- include: install.yml
  tags:
    - crayfish
    - crayfish-install
