---

apix_feature_repo: mvn:org.fcrepo.apix/fcrepo-api-x-karaf/LATEST/xml/features
apix_feature:
  - fcrepo-api-x
  - fcrepo-indexing-triplestore
  - fcrepo-service-camel

apix_karaf_etc_dir: "{{ karaf_install_symlink }}/etc"

apix_config:
  - pid: org.fcrepo.apix.registry.http
    settings:
      timeout.socket.ms: 1000
  - pid: org.fcrepo.camel.indexing.triplestore
    settings:
      input.stream: activemq:topic:fedora
      triplestore.reindex.stream: activemq:queue:triplestore.reindex
      triplestore.baseUrl: http://localhost:8080/bigdata/namespace/islandora/sparql
