---

- hosts: webserver
  become: yes

  # add some vars here so we can run with --start-at-task if desired
  vars:
    webserver_app_user: "{% if ansible_os_family == 'RedHat' %}apache{% else %}www-data{% endif %}"
    vagrant_user: "{% if ansible_os_family == 'RedHat' %}vagrant{% else %}ubuntu{% endif %}"

  tasks:
    # Some tomfoolery to get the demo module to install.
    # Subject to https://www.drupal.org/node/2599228
    # Should be fixed in Drupal 8.7
    - name: Install demo module (fail ok)
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y en islandora_demo"
      ignore_errors: yes
    - name: Update entities
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y entity:updates"
    - name: Uninstall demo module
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y pmu islandora_demo"
    - name: Install demo module (should not fail)
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y en islandora_demo"
    - name: Import feature
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y fim --bundle=islandora islandora_demo"
    - name: Add admin to fedoraAdmin role
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y urol fedoraadmin admin"

    - name: Run migrations
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y -l localhost:{{ apache_listen_port }} --userid=1 mim --group=islandora"

    - name: Add vagrant user to webserver app user group
      user: name={{ vagrant_user }}
            group={{ webserver_app_user }}
            append=yes

    - name: Create the default files simpletest directory
      file: 
        path: "{{ drupal_public_filesystem }}/simpletest"
        state: directory
        owner: "{{ webserver_app_user }}"
        group: "{{ webserver_app_user }}"
        mode: 0775
        recurse: yes

    - name: Create the sites simpletest directory
      file: 
        path: "{{ drupal_core_path }}/sites/simpletest"
        state: directory
        owner: "{{ webserver_app_user }}"
        group: "{{ webserver_app_user }}"
        mode: 0775
        recurse: yes
    
    - name: Chown islandora core feature
      file:
        dest: "{{ drupal_core_path }}/modules/contrib/islandora/modules/islandora_core_feature"
        state: directory
        owner: "{{ webserver_app_user }}"
        group: "{{ webserver_app_user }}"
        mode: 0775
        recurse: yes

    - name: Chown islandora demo feature
      file:
        dest: "{{ drupal_core_path }}/modules/contrib/islandora_demo"
        state: directory
        owner: "{{ webserver_app_user }}"
        group: "{{ webserver_app_user }}"
        mode: 0775
        recurse: yes

    - name: Chown controlled access terms default configuration
      file:
        dest: "{{ drupal_core_path }}/modules/contrib/controlled_access_terms/modules/controlled_access_terms_default_configuration"
        state: directory
        owner: "{{ webserver_app_user }}"
        group: "{{ webserver_app_user }}"
        mode: 0775
        recurse: yes
