---

- name: Add Alpaca Repos (source)
  karaf_repo:
    state: present
    name: file:{{ alpaca_clone_directory }}/karaf/build/resources/main/features.xml
  when: alpaca_from_source

- name: Add Alpaca Repos (package)
  karaf_repo:
    state: present
    name: "{{ item }}"
  with_items: "{{ alpaca_karaf_repos }}"
  when: not alpaca_from_source

- name: Add Alpaca Features
  karaf_feature:
    state: present
    name: "{{ item }}"
  with_items: "{{ alpaca_features }}"
