---

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family}}.yml"

- name: Define karaf_java_home
  set_fact:
    karaf_java_home: "{{ __karaf_java_home }}"
  when: karaf_java_home is not defined

- name: Define karaf_java_packages
  set_fact:
    karaf_java_packages: "{{ __karaf_java_packages }}"
  when: karaf_java_packages is not defined

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 600
  when: ansible_os_family == "Debian"

- name: Install Java packages
  package:
    name: "{{ karaf_java_packages|join(',') }}"
    state: present

- name: Expand Karaf Tarball
  unarchive:
    src: "{{ karaf_staging_folder }}/apache-karaf-{{ karaf_version }}.tar.gz"
    dest: "{{ karaf_install_folder }}"
    owner: "{{ karaf_user }}"
    group: "{{ karaf_user }}"
    remote_src: yes
    creates: "{{ karaf_install_folder }}/apache-karaf-{{ karaf_version }}"

- name: Set Karaf Permissions
  file:
    state: directory
    path: "{{ karaf_install_folder }}/apache-karaf-{{ karaf_version }}"
    owner: "{{ karaf_user }}"
    group: "{{ karaf_user }}"

- name: Make Karaf Symlink
  file:
    state: link
    src: "{{ karaf_install_folder }}/apache-karaf-{{ karaf_version }}"
    dest: "{{ karaf_install_symlink }}"
    owner: "{{ karaf_user }}"
    group: "{{ karaf_user }}"
