---

- name: Copy setenv script
  template:
    src: setenv.j2
    dest: "{{ karaf_install_symlink }}/bin/setenv"
    owner: "{{ karaf_user }}"
    group: "{{ karaf_user }}"

- name: Start Karaf
  shell: >
    {{ karaf_install_symlink }}/bin/start && sleep 5
  args:
    chdir: "{{ karaf_install_symlink }}/bin"
    creates: "{{ karaf_install_symlink }}/bin/karaf-wrapper"
  register: karaf_service_install

- name: Wait for Karaf to start
  wait_for:
    port: 8101
  when: karaf_service_install.changed is defined and karaf_service_install.changed

- name: Install wrapper feature
  command: ./client feature:install wrapper
  args:
    chdir: "{{ karaf_install_symlink }}/bin"
  when: karaf_service_install.changed is defined and karaf_service_install.changed

- name: Install wrapper
  command: ./client wrapper:install
  args:
    chdir: "{{ karaf_install_symlink }}/bin"
  when: karaf_service_install.changed is defined and karaf_service_install.changed

- name: Stop Karaf
  shell: >
    {{ karaf_install_symlink }}/bin/stop && sleep 1
  args:
    chdir: "{{ karaf_install_symlink }}/bin"
  when: karaf_service_install.changed is defined and karaf_service_install.changed
