---

- name: Copy templated Karaf definition
  template:
    src: "{{ karaf_systemd_template }}"
    dest: "{{ karaf_install_symlink }}/bin/karaf.service"
    owner: "{{ karaf_user }}"
    group: "{{ karaf_user }}"

- name: Install Karaf service in systemd
  command: systemctl enable {{ karaf_install_symlink }}/bin/karaf.service
  args:
    creates: /etc/systemd/system/karaf

- name: Start Karaf service
  service:
    name: karaf
    state: started
  register: karaf_start_karaf

- name: Wait for Karaf to start
  wait_for:
    port: 8101
  when: karaf_start_karaf.changed
