---

- name: template /etc/default/tomcat8
  template:
    src: tomcat-defaults.j2
    dest: /etc/default/tomcat8
  notify: restart tomcat8
  when: ansible_os_family == 'Debian'

- name: template {{tomcat8_home}}/bin/setenv.sh
  template:
    src: setenv.sh.j2
    dest: "{{tomcat8_home}}/bin/setenv.sh"
  notify: restart tomcat8
  when: ansible_os_family == 'RedHat'

- name: server configuration
  template:
    src: server.xml.j2
    dest: "{{tomcat8_home}}/conf/server.xml"
  notify: restart tomcat8
  sudo: True

- name: template tomcat-users.xml
  template:
    src: tomcat-users.xml.j2
    dest: "{{tomcat8_home}}/conf/tomcat-users.xml"
    owner: "{{ tomcat8_server_user }}"
    group: "{{ tomcat8_server_group }}"
    mode: "640"
  notify: restart tomcat8

- name: start tomcat
  service:
    name: "{{tomcat_service_name}}"
    state: started
    enabled: yes
  sudo: True
