---

- name: group add
  group:
    name: "{{ tomcat8_server_group }}"
  sudo: True


- name: user add
  user:
    name: "{{ tomcat8_server_user }}"
    group: "{{ tomcat8_server_group }}"
    home: "{{ tomcat8_user_home }}"
    createhome: no
  sudo: True

- name: download and extract
  unarchive:
    src: "{{ tomcat_binary_url }}"
    dest: "/opt/"
    remote_src: yes
  sudo: True

- name: symlink install directory
  file:
    src: "{{ tomcat_target_dir }}"
    path: "{{ tomcat8_home }}"
    state: link
  sudo: True

- name: change ownership of target installation
  file:
    path: "{{ tomcat_target_dir }}"
    owner: "{{ tomcat8_server_user }}"
    group: "{{ tomcat8_server_group }}"
    state: directory
    recurse: yes
  sudo: True

- name: systemd
  template: src=tomcat.service.j2 dest=/etc/systemd/system/tomcat8.service
  notify: restart tomcat8
  sudo: True
