---

- name: Add API-X Repos
  karaf_repo:
    state: present
    name: "{{ item }}"
  with_items: "{{ apix_feature_repo }}"

- name: Add API-X Features
  karaf_feature:
    state: present
    name: "{{ item }}"
  with_items: "{{ apix_feature }}"
