---

- name: Create Gemini DB (mysql)
  mysql_db:
    name: "{{ crayfish_db_name }}"
    state: present
  register: gemini_db_exists

- name: Create Gemini DB User (mysql)
  mysql_user:
    name: "{{ crayfish_db_user }}"
    password: "{{ crayfish_db_password }}"
    state: present
    priv: "{{crayfish_db_name}}.*:ALL"
