tomcat8_packages:
  - tomcat8
tomcat8_admin_packages:
  - tomcat8-admin

tomcat_service_name:   tomcat8

tomcat8_admin_install: yes

tomcat8_roles: []
tomcat8_users: []

tomcat8_server_user: tomcat8
tomcat8_server_group: tomcat8
tomcat8_user_home: /home/tomcat8

# The home directory of the Java development kit (JDK). You need at least
# JDK version 7. If JAVA_HOME is not set, some common directories for
# OpenJDK and the Oracle JDK are tried.
#tomcat8_java_home:

# You may pass JVM startup parameters to Java here. If unset, the default
# options will be: -Djava.awt.headless=true -Xmx128m -XX:+UseConcMarkSweepGC
tomcat8_java_opts:
  - -Djava.awt.headless=true
  - -Xmx128m
  - -XX:+UseConcMarkSweepGC

# Java compiler to use for translating JavaServer Pages (JSPs). You can use all
# compilers that are accepted by Ant's build.compiler property.
#tomcat8_jsp_compiler: javac

# Use the Java security manager? (yes/no, default: no)
#tomcat8_tomcat8_security: "no"

# Number of days to keep logfiles in /var/log/tomcat8. Default is 14 days.
#tomcat8_logfile_days: 14

# Whether to compress logfiles older than today's
#tomcat8_logfile_compress: 1

# Location of the JVM temporary directory
# WARNING: This directory will be destroyed and recreated at every startup !
#tomcat8_jvm_tmp: /tmp/tomcat8-temp

# If you run Tomcat on port numbers that are all higher than 1023, then you
# do not need authbind.  It is used for binding Tomcat to lower port numbers.
# (yes/no, default: no)
#tomcat8_authbind: no

# Some OS-specific variables are set in vars/* but can be overridden here:
# tomcat8_home: /opt/tomcat
#
# Tomcat binary to dl and related path (For installing binaries on CentOS/RH)
# tomcat8_version: 8.5.27
# tomcat_binary_url:  "http://www-eu.apache.org/dist/tomcat/tomcat-8/v{{ tomcat8_version }}/bin/apache-tomcat-{{ tomcat8_version }}.tar.gz"
# tomcat_target_dir:  "/opt/apache-tomcat-{{ tomcat8_version }}"
