---

- name: Template settings
  template:
    src: alpaca.cfg.j2
    dest: "{{ alpaca_karaf_etc_dir }}/{{ item.pid }}.cfg"
  with_items: "{{ alpaca_settings }}"

- name: Template blueprint files
  template:
    src: blueprint.xml.j2
    dest: "{{ alpaca_karaf_deploy_dir }}/{{ item.pid }}.blueprint.xml"
  with_items: "{{ alpaca_blueprint_settings }}"
