# TODO: find a better way here, this is ugly and will bite us
- name: Set fits.home in catalina.properties
  lineinfile:
    path: "{{ tomcat8_home }}/conf/catalina.properties"
    regexp: "^fits.home="
    line: "fits.home={{ fits_install_symlink }}"
  notify: restart tomcat8

- name: Set shared.loader in catalina.properties
  lineinfile:
    path: "{{ tomcat8_home }}/conf/catalina.properties"
    line: 'shared.loader=${fits.home}/lib/*.jar'
  notify: restart tomcat8
