---

- hosts: webserver
  become: yes
  vars:
    php_enablerepo: "remi-php70"
    php_packages_state: "latest"

  roles:
    - name: geerlingguy.repo-remi
      when: ansible_os_family == "RedHat"
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.git
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.drupal-console
    - geerlingguy.drupal
    - Islandora-Devops.drupal-openseadragon
    - webserver-app
