---

drupal_build_composer_project: true
drupal_composer_install_dir: /var/www/html/drupal
drupal_core_owner: "{{ ansible_user }}"
drupal_composer_dependencies:
  - "drupal/console:~1.0"
  - "drupal/devel:^1.0@beta"
  - "drupal/rdfui:1.x-dev"
  - "drupal/restui:^1.13"
  - "drupal/media_entity:^1.6"
  - "drupal/media_entity_image:^1.2"
  - "drupal/search_api_solr:1.0.0"
  - "drupal/facets:1.x-dev"
  - "islandora/carapace:dev-8.x-1.x"
  - "islandora/islandora_image:dev-8.x-1.x"
drupal_composer_project_package: "islandora/drupal-project:8.4"
drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"
drupal_core_path: "{{ drupal_composer_install_dir }}/web"
drupal_db_user: drupal8
drupal_db_name: drupal8
drupal_db_backend: "{{ claw_db }}"
drupal_db_host: "127.0.0.1"
drupal_domain: "claw.dev"
drupal_site_name: "Islandora-CLAW"
drupal_install_profile: standard
drupal_account_name: admin
drupal_enable_modules:
  - rdf
  - responsive_image
  - syslog
  - serialization
  - basic_auth
  - rest
  - simpletest
  - restui
  - media_entity
  - media_entity_image
  - devel
  - search_api
  - islandora_image
  - search_api_solr
  - search_api_solr_defaults
  - facets
drupal_trusted_hosts:
  - ^localhost$
  - ^claw.dev$
drupal_trusted_hosts_file: "{{ drupal_core_path }}/sites/default/settings.php"
drupal_public_filesystem: "{{ drupal_core_path }}/sites/default/files"
