---

- name: Create JWT Key Path
  file:
    state: directory
    path: "{{ ssl_key_directory }}"

- name: Create JWT Private Key
  command: openssl genrsa -out "{{ ssl_key_directory }}/{{ ssl_key_private_file }}" 2048
  args:
    creates: "{{ ssl_key_directory }}/{{ ssl_key_private_file }}"

- name: Create JWT Public Key
  command: openssl rsa -pubout -in "{{ ssl_key_directory }}/{{ ssl_key_private_file }}" -out "{{ ssl_key_directory }}/{{ ssl_key_public_file }}"
  args:
    creates: "{{ ssl_key_directory }}/{{ ssl_key_public_file }}"

- name: Copy public key out
  copy:
    src: "{{ ssl_key_directory }}/{{ ssl_key_public_file }}"
    dest: "{{ ssl_key_public_output_path }}"
    mode: 0644
    remote_src: yes
    
- name: Copy private key out
  copy:
    src: "{{ ssl_key_directory }}/{{ ssl_key_private_file }}"
    dest: "{{ ssl_key_private_output_path }}"
    mode: 0644
    remote_src: true
