---

- name: Wait for blazegraph to expand
  wait_for:
    path: "{{blazegraph_log4j_path}}"
    state: present

- name: Copy the templated log4j config
  template:
    src: "{{ blazegraph_log4j_template }}"
    dest: "{{blazegraph_log4j_path}}"
    owner: "{{ blazegraph_user }}"
    group: "{{ blazegraph_user }}"
  notify: restart tomcat8
